# Netlify configuration for Next.js 15 + Supabase game - force refresh
[build]
  command = "npm ci --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.1"
  NPM_VERSION = "10.9.2"

[functions]
  node_bundler = "esbuild"

# Plugin is configured in Netlify UI, removing from here to avoid conflict

[build.cache]
  paths = [ 
    "node_modules/.cache",
    ".next/cache"
  ]

[context.production.environment]
  NODE_VERSION = "20.19.1"

[context.deploy-preview.environment]
  NODE_VERSION = "20.19.1"
