-- Calibration seeds generated from the approved workbook.

insert into public.content_motif_cooldowns (motif, status, reason, replacement_direction) values
  ('Courts / subpoenas / evidence / police reports', 'cooldown', 'Became a visible default skeleton.', 'Attack the reward, use a physical image, or corrupt the output.'),
  ('HR / performance reviews', 'cooldown', 'Overrepresented in the old deck and early generations.', 'Use social status, public ritual, or bizarre service conditions.'),
  ('Taxes / IRS / subscriptions / overdraft fees', 'cooldown', 'Financial penalties alone often lacked a joke.', 'Keep money but force obscene or immoral spending.'),
  ('Parents / spouse recognizes it / ex', 'cooldown', 'Efficient but repetitive relationship shortcut.', 'Use strangers, institutions, audiences, or unexplained consequences.'),
  ('Tattoos / browser history', 'cooldown', 'Recognizable AI-comedy crutch.', 'Invent a fresh concrete object or sensory detail.'),
  ('Funerals', 'limited', 'Some good keeps, but used too often as arbitrary timing.', 'Use less obvious events, destinations, or public rituals.'),
  ('Masturbation / erections / bowel movements', 'limited', 'Still effective, but repetition becomes obvious fast.', 'Rotate with food, animals, labor, religion, travel, and bodily care.'),
  ('Named celebrities / topical politicians', 'use_sparingly', 'Can date quickly or create verification issues.', 'Prefer role-based descriptions unless topicality is the point.'),
  ('Random cruelty to children/animals', 'use_sparingly', 'Darkness without a comedic turn feels manufactured.', 'Tie the moral cost directly to the benefit or power.'),
  ('Same stem repeated in a batch', 'banned_in_batch', 'Makes the generator feel mechanical.', 'No more than two candidates with the same opening structure.')
on conflict (motif) do update set status = excluded.status, reason = excluded.reason, replacement_direction = excluded.replacement_direction, is_active = true;

insert into public.content_reference_examples (response_text, verdict, origin, source_category, source_scenario, source_scenario_id, notes) values
  ('but you always arrive during the worst thirty seconds of someone else''s life.', 'approved', 'AI', 'Super Powers', 'You can teleport anywhere instantly', '2f3ff257-ee3c-477f-8546-7547a1af0ec8'::uuid, null),
  ('but you arrive naked, aroused, and already apologizing.', 'approved', 'AI', 'Super Powers', 'You can teleport anywhere instantly', '2f3ff257-ee3c-477f-8546-7547a1af0ec8'::uuid, null),
  ('but each use gives a random toddler one of your memories.', 'approved', 'AI', 'Super Powers', 'You can teleport anywhere instantly', '2f3ff257-ee3c-477f-8546-7547a1af0ec8'::uuid, null),
  ('but every erection is now considered structural damage.', 'approved', 'AI', 'Super Powers', 'You develop super strength overnight', 'c80c7b9c-2d80-4b0d-99c9-11de5583a187'::uuid, null),
  ('but it only works when you''re genuinely trying not to cry.', 'approved', 'AI', 'Super Powers', 'You develop super strength overnight', 'c80c7b9c-2d80-4b0d-99c9-11de5583a187'::uuid, null),
  ('but every high five becomes a workers'' compensation claim.', 'approved', 'AI', 'Super Powers', 'You develop super strength overnight', 'c80c7b9c-2d80-4b0d-99c9-11de5583a187'::uuid, null),
  ('but you can only lift your mom.', 'approved', 'User', 'Super Powers', 'You develop super strength overnight', 'c80c7b9c-2d80-4b0d-99c9-11de5583a187'::uuid, null),
  ('and it also makes you super racist.', 'approved', 'User', 'Super Powers', 'You develop super strength overnight', 'c80c7b9c-2d80-4b0d-99c9-11de5583a187'::uuid, null),
  ('but it only speaks during sex, and it has notes.', 'approved', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, null),
  ('but everything it says begins with, “According to the police report...”', 'approved', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, null),
  ('and it also becomes extremely racist.', 'approved', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, null),
  ('Good news: it loves you. Bad news: it has witnesses.', 'approved', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, null),
  ('but every secret it reveals earns it a small piece of cheese.', 'approved', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, null),
  ('but every time it saves you, a Make-A-Wish kid loses a day.', 'approved', 'AI', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('you still age. You just stop dying.', 'approved', 'AI', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('but it only works while you''re naked and screaming your Social Security number.', 'approved', 'AI', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('but you still have to go to work tomorrow.', 'approved', 'AI', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('it also makes you sexually attracted to taxidermy.', 'approved', 'AI', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('but it only works inside porta-potties in August.', 'approved', 'User', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('only during funerals.', 'approved', 'User', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('to activate it, you have to kill six kittens.', 'approved', 'User', 'Super Powers', 'You become completely immortal', '5fb02a44-6fff-4c0c-a6b7-549141de264d'::uuid, null),
  ('but every copy comes out warm, wet, and breathing.', 'approved', 'AI', 'Super Powers', 'You can duplicate any object by touching it', 'b42bec06-93b1-42ee-b816-6a9725812875'::uuid, null),
  ('only during open-casket funerals.', 'approved', 'AI', 'Super Powers', 'You can duplicate any object by touching it', 'b42bec06-93b1-42ee-b816-6a9725812875'::uuid, null),
  ('but it only works while you''re actively shitting your pants.', 'approved', 'AI', 'Super Powers', 'You gain the power to control time', '156c2da4-f97b-4d77-94c0-e22e7a3a6ef7'::uuid, null),
  ('but every use makes one random elderly person shit themselves.', 'approved', 'AI', 'Super Powers', 'You gain the power to control time', '156c2da4-f97b-4d77-94c0-e22e7a3a6ef7'::uuid, null),
  ('and somewhere, a priest has to watch.', 'approved', 'AI', 'Super Powers', 'You gain the power to control time', '156c2da4-f97b-4d77-94c0-e22e7a3a6ef7'::uuid, null),
  ('if you also figure out how to find the clitoris.', 'approved', 'User', 'Super Powers', 'You gain the power to control time', '156c2da4-f97b-4d77-94c0-e22e7a3a6ef7'::uuid, null),
  ('but only while someone nearby is masturbating.', 'approved', 'AI', 'Super Powers', 'You can read minds', null, null),
  ('only in church bathrooms.', 'approved', 'AI', 'Super Powers', 'You can read minds', null, null),
  ('and every compliment ends with “for your age.”', 'approved', 'AI', 'Life Things', 'You wake up as the most attractive person alive', null, null),
  ('and your voice now sounds like a child faking an orgasm.', 'approved', 'AI', 'Life Things', 'You wake up as the most attractive person alive', null, null),
  ('but you''re only attractive to horses.', 'approved', 'AI', 'Life Things', 'You wake up as the most attractive person alive', null, null),
  ('to prison inmates.', 'approved', 'User', 'Life Things', 'You wake up as the most attractive person alive', null, null),
  ('only while maintaining an erection.', 'approved', 'AI', 'Super Powers', 'You can turn invisible at will', null, null),
  ('but dogs bark your full legal name.', 'approved', 'AI', 'Super Powers', 'You can turn invisible at will', null, null),
  ('but mirrors show what you''re thinking.', 'approved', 'AI', 'Super Powers', 'You can turn invisible at will', null, null),
  ('but only in toilets.', 'approved', 'AI', 'Super Powers', 'You can breathe underwater', null, null),
  ('and dolphins become sexually aggressive.', 'approved', 'AI', 'Super Powers', 'You can breathe underwater', null, null),
  ('only while someone else is drowning.', 'approved', 'AI', 'Super Powers', 'You can breathe underwater', null, null),
  ('but only while your spouse suffers from crippling depression.', 'approved', 'User', 'Super Powers', 'You can breathe underwater', null, null),
  ('but your boss is asleep beside you.', 'approved', 'AI', 'Life Things', 'You wake up completely refreshed', null, null),
  ('but the rest of your family didn''t wake up.', 'approved', 'AI', 'Life Things', 'You wake up completely refreshed', null, null),
  ('but all the bills have your nude body printed on them.', 'approved', 'AI', 'Life Things', 'You win the lottery jackpot', '7d7568db-b665-45a6-9c65-d992232d0504'::uuid, null),
  ('and a live studio audience follows you everywhere.', 'approved', 'AI', 'Life Things', 'You win the lottery jackpot', '7d7568db-b665-45a6-9c65-d992232d0504'::uuid, null),
  ('but the raise is paid entirely in Chili''s gift cards.', 'approved', 'AI', 'Life Things', 'You get promoted at work', null, null),
  ('but you can only exercise authority while wearing assless chaps.', 'approved', 'AI', 'Life Things', 'You get promoted at work', null, null),
  ('but it only speaks in your mother''s disappointed voice.', 'approved', 'AI', 'Absurd & Surreal', 'Your reflection starts talking to you', null, null),
  ('but every sentence ends with, “and that''s why she left.”', 'approved', 'AI', 'Absurd & Surreal', 'Your reflection starts talking to you', null, null),
  ('only while you''re crying in a public restroom.', 'approved', 'AI', 'Absurd & Surreal', 'Your reflection starts talking to you', null, null),
  ('and it hates you and your pants.', 'approved', 'User', 'Absurd & Surreal', 'Your reflection starts talking to you', null, null),
  ('and your name becomes a verb for shitting yourself in public.', 'approved', 'AI', 'Pop Culture & Internet', 'You become the internet''s main character overnight', null, null),
  ('but only on AOL.', 'approved', 'Edited', 'Pop Culture & Internet', 'You become the internet''s main character overnight', null, null),
  ('but every attempt produces a middle manager.', 'approved', 'AI', 'Super Powers', 'You gain the ability to create life', '5d9c4f28-1b1e-432f-aa27-df6e8579ec44'::uuid, null),
  ('only from the waist down.', 'approved', 'AI', 'Absurd & Surreal', 'You start glowing in the dark', '0b17a91c-ede3-4410-938d-68b4c06e9a65'::uuid, null),
  ('and your nipples blink in Morse code.', 'approved', 'AI', 'Absurd & Surreal', 'You start glowing in the dark', '0b17a91c-ede3-4410-938d-68b4c06e9a65'::uuid, null),
  ('only when someone says “moist.”', 'approved', 'AI', 'Absurd & Surreal', 'You start glowing in the dark', '0b17a91c-ede3-4410-938d-68b4c06e9a65'::uuid, null),
  ('only if you agree to be hunted for sport once a year.', 'approved', 'AI', 'Life Things', 'You get your dream job', 'afc71605-ab3e-4f63-9e62-bf3eafe33415'::uuid, null),
  ('but everyone is subscribed to your OnlyFans.', 'approved', 'Edited', 'Life Things', 'You get your dream job', 'afc71605-ab3e-4f63-9e62-bf3eafe33415'::uuid, null),
  ('but HR communicates exclusively through ransom notes.', 'approved', 'AI', 'Life Things', 'You get your dream job', 'afc71605-ab3e-4f63-9e62-bf3eafe33415'::uuid, null),
  ('but only in North Korean propaganda.', 'approved', 'AI', 'Pop Culture & Internet', 'You become a viral meme', null, null),
  ('but the original photo was taken during your colonoscopy.', 'approved', 'AI', 'Pop Culture & Internet', 'You become a viral meme', null, null),
  ('and your funeral gets ratioed.', 'approved', 'AI', 'Pop Culture & Internet', 'You become a viral meme', null, null),
  ('but only because you slapped that nun on the ass at the Vatican.', 'approved', 'User', 'Pop Culture & Internet', 'You become a viral meme', null, null),
  ('only because the caterer needs an organ donor.', 'approved', 'AI', 'Pop Culture & Internet', 'You get invited to an exclusive celebrity party', null, null),
  ('but you were asked to bring two dozen bottles of baby oil...for reasons.', 'approved', 'User', 'Pop Culture & Internet', 'You get invited to an exclusive celebrity party', null, null),
  ('but everyone remembers you for the same bowel movement.', 'approved', 'AI', 'Life Things', 'You get invited to your high school reunion as the success story', '1fdb3495-ce5d-45fb-8015-3e7297fe4677'::uuid, null),
  ('but it''s for your outstanding achievements in adult film.', 'approved', 'User', 'Life Things', 'You get invited to your high school reunion as the success story', '1fdb3495-ce5d-45fb-8015-3e7297fe4677'::uuid, null),
  ('but the neighborhood votes to turn it into a Spirit Halloween.', 'approved', 'AI', 'Life Things', 'You finally pay off your house', null, null),
  ('but it''s immediately selected as the set for a gangbang.', 'approved', 'AI', 'Life Things', 'You finally pay off your house', null, null),
  ('but you can only spend the remaining money on hair extensions for pedophiles.', 'approved', 'User', 'Life Things', 'You finally pay off your house', null, null),
  ('and your dog has already chosen a new family.', 'approved', 'AI', 'Life Things', 'You just had the greatest vacation of your life', null, null),
  ('and tomorrow you start waxing cadavers again.', 'approved', 'AI', 'Life Things', 'You just had the greatest vacation of your life', null, null),
  ('and “horny” is permanently stuck on maximum.', 'approved', 'AI', 'Super Powers', 'You can control people''s emotions', '12d1d94c-65ef-4bee-aae5-935cf776d0c2'::uuid, null),
  ('but everyone directs those feelings toward the nearest horse.', 'approved', 'AI', 'Super Powers', 'You can control people''s emotions', '12d1d94c-65ef-4bee-aae5-935cf776d0c2'::uuid, null),
  ('and guilt is permanently set to “Catholic.”', 'approved', 'AI', 'Super Powers', 'You can control people''s emotions', '12d1d94c-65ef-4bee-aae5-935cf776d0c2'::uuid, null),
  ('and nobody can feel anything while wearing Crocs.', 'approved', 'AI', 'Super Powers', 'You can control people''s emotions', '12d1d94c-65ef-4bee-aae5-935cf776d0c2'::uuid, null),
  ('but every item has already been opened and sniffed.', 'approved', 'AI', 'Life Things', 'You win a contest for a year''s worth of free groceries', '2f233dfa-46f5-4713-9a49-4e9028ee1aea'::uuid, null),
  ('and the cashier has to watch you eat everything.', 'approved', 'AI', 'Life Things', 'You win a contest for a year''s worth of free groceries', '2f233dfa-46f5-4713-9a49-4e9028ee1aea'::uuid, null),
  ('but all the meat comes with a first name.', 'approved', 'AI', 'Life Things', 'You win a contest for a year''s worth of free groceries', '2f233dfa-46f5-4713-9a49-4e9028ee1aea'::uuid, null),
  ('only at gas stations where the bathroom key is attached to a brick.', 'approved', 'AI', 'Life Things', 'You win a contest for a year''s worth of free groceries', '2f233dfa-46f5-4713-9a49-4e9028ee1aea'::uuid, null),
  ('and every room contains the same naked man.', 'approved', 'AI', 'Life Things', 'You find the perfect apartment', '7e54faee-a187-4c9a-9a94-751e5ee00223'::uuid, null),
  ('but the rent can only be paid in human teeth.', 'approved', 'AI', 'Life Things', 'You find the perfect apartment', '7e54faee-a187-4c9a-9a94-751e5ee00223'::uuid, null),
  ('only if you livestream every bowel movement.', 'approved', 'AI', 'Life Things', 'You find the perfect apartment', '7e54faee-a187-4c9a-9a94-751e5ee00223'::uuid, null),
  ('but the walls loudly repeat anything said during sex.', 'approved', 'AI', 'Life Things', 'You find the perfect apartment', '7e54faee-a187-4c9a-9a94-751e5ee00223'::uuid, null),
  ('but only at nursing homes during sponge baths.', 'approved', 'AI', 'Life Things', 'You win free internet for life', '2e8d1d43-8eb8-4da9-9e6c-a7236697bb01'::uuid, null),
  ('and every search is read aloud by a furious auctioneer.', 'approved', 'AI', 'Life Things', 'You win free internet for life', '2e8d1d43-8eb8-4da9-9e6c-a7236697bb01'::uuid, null),
  ('only while wearing someone else''s dentures.', 'approved', 'AI', 'Life Things', 'You win free internet for life', '2e8d1d43-8eb8-4da9-9e6c-a7236697bb01'::uuid, null),
  ('but the password changes whenever you get an erection.', 'approved', 'AI', 'Life Things', 'You win free internet for life', '2e8d1d43-8eb8-4da9-9e6c-a7236697bb01'::uuid, null),
  ('and all porn is replaced with footage from your own birth.', 'approved', 'AI', 'Life Things', 'You win free internet for life', '2e8d1d43-8eb8-4da9-9e6c-a7236697bb01'::uuid, null),
  ('but every truth sounds like a pickup line.', 'approved', 'AI', 'Life Things', 'You can no longer lie', null, null),
  ('only while carrying a live ferret.', 'approved', 'AI', 'Life Things', 'You never have to wait in line again', null, null),
  ('only if you loudly explain your last bowel movement.', 'approved', 'AI', 'Life Things', 'You never have to wait in line again', null, null),
  ('and somewhere, a Make-A-Wish kid gets sent to the back.', 'approved', 'AI', 'Life Things', 'You never have to wait in line again', null, null),
  ('but they only take instructions while sitting on your lap.', 'approved', 'AI', 'Life Things', 'You get your own personal assistant', null, null),
  ('and they introduce you everywhere as “Vice President Piss-Pants.”', 'approved', 'Edited', 'Life Things', 'You get your own personal assistant', null, null),
  ('but they have to feed you lunch like a mother bird.', 'approved', 'Edited', 'Life Things', 'You get your own personal assistant', null, null),
  ('only while dressed as a Civil War widow.', 'approved', 'AI', 'Life Things', 'You get free first-class flights for life', null, null),
  ('but every meal is pre-chewed by the flight attendant.', 'approved', 'AI', 'Life Things', 'You get free first-class flights for life', null, null),
  ('and the cabin applauds whenever you use the bathroom.', 'approved', 'AI', 'Life Things', 'You get free first-class flights for life', null, null),
  ('but every meal is served in a dog bowl.', 'approved', 'AI', 'Life Things', 'You never have to cook again', null, null),
  ('and every dessert contains one human tooth.', 'approved', 'AI', 'Life Things', 'You never have to cook again', null, null),
  ('and the food screams when you cut it.', 'approved', 'AI', 'Life Things', 'You never have to cook again', null, null),
  ('but every meal makes your elderly cousin send you a dick pic.', 'approved', 'User', 'Life Things', 'You never have to cook again', null, null),
  ('but you wake up spooning a mall Santa.', 'approved', 'AI', 'Life Things', 'You finally get eight hours of sleep', null, null),
  ('and a hospice nurse is standing there looking surprised.', 'approved', 'AI', 'Life Things', 'You finally get eight hours of sleep', null, null),
  ('and every morning starts with a mandatory nude fire drill.', 'approved', 'AI', 'Life Things', 'You get to retire early', null, null),
  ('but now you''re the emotional-support animal for a lonely trucker.', 'approved', 'Edited', 'Life Things', 'You get to retire early', null, null),
  ('and your farewell cake contains a working human eye.', 'approved', 'AI', 'Life Things', 'You get to retire early', null, null),
  ('and everyone calls you “Grandpa Cum-Socks.”', 'approved', 'AI', 'Life Things', 'You get to retire early', null, null),
  ('but it sounds exactly like the relative whose ashes it knocked off the shelf.', 'maybe', 'AI', 'Absurd & Surreal', 'You discover your pet can talk', 'eaf82280-b674-4313-8716-2fcd31cbbb11'::uuid, 'Funny, but too specific to this scenario.'),
  ('but everyone remembers you screaming a racial slur at a children''s hospital.', 'maybe', 'AI', 'Super Powers', 'You gain the power to control time', '156c2da4-f97b-4d77-94c0-e22e7a3a6ef7'::uuid, 'User said it was fine but was still thinking about it.'),
  ('but all you hear is Portuguese.', 'reference', 'User', 'Super Powers', 'You can read minds', null, 'Good corrupted-output structure; avoid repeating this exact language.'),
  ('but the voice in your head is just Fran Drescher laughing.', 'reference', 'User', 'Super Powers', 'You can read minds', null, 'Strong structure; dated celebrity reference.'),
  ('but you can only spend it while being pegged by an adult witch.', 'needs_rewrite', 'Edited', 'Life Things', 'You win the lottery jackpot', '7d7568db-b665-45a6-9c65-d992232d0504'::uuid, 'Adult-safe rewrite of the user''s fictional-character example; spicy pass later.'),
  ('but tomorrow you go back to being Satan''s proctologist.', 'maybe', 'AI', 'Life Things', 'You just had the greatest vacation of your life', null, 'User said this was okay.'),
  ('but the destination is always a timeshare presentation.', 'reference', 'AI', 'Life Things', 'You get free first-class flights for life', null, 'Suggested after user requested a terrible destination; not explicitly approved.')
on conflict (lower(trim(response_text))) do update set verdict = excluded.verdict, origin = excluded.origin, source_category = excluded.source_category, source_scenario = excluded.source_scenario, source_scenario_id = excluded.source_scenario_id, notes = excluded.notes, is_active = true;
